### PR TITLE
Add support for custom html

### PR DESCRIPTION
**Pull request by CraigChamberlain**

### CODE REVIEW

**Comment by CraigChamberlain** [comment]
It's good to have popups linking to other pages and maybe display an image.  It seems Label might be at odds with html, I don't know if you can pup them as mutually exclusive in parameter sets?  I made it so if the customHtml prop has any content the label is ignored.

I don't think other props are too important.
https://docs.mapbox.com/mapbox-gl-js/api/markers/#popup

Popup with custom html
image

Example Code
image

**Comment by antony** [comment]
Is this superseded by the PR I just merged?

**Comment by CraigChamberlain** [comment]
Yes

**Comment by CraigChamberlain** [comment]
Should I add some info to the docs and do another PR?

**Pull request closed without merging**
