### PR TITLE
Proposed MIT license :) 

### PR DESCRIPTION
**Pull request by brittharr**

### CODE REVIEW

**Comment by mojodna** [comment]
+1

Please document the license that this library is released under.

**Comment by antony** [comment]
thanks @brittharr !

**Comment by antony** [comment]
@mojodna will do asap - thanks!

**Comment by mojodna** [comment]
I see a commit for 8.2.0 but don’t see it in npm under `@beyonk/svelte-mapbox`. Am I missing something?

Sorry to be troublesome; I’m just really looking forward to being able to use this library! Thank you for your fantastic work.

**Comment by antony** [comment]
Hi @mojodna apologies - I had an old NPM token which required 2FA in the project. I've deleted it and the publish has now succeeded.

**Pull request merged**
