### PR TITLE
Add details for new Marker Features

### PR DESCRIPTION
**Pull request by CraigChamberlain**
Docs for features added in 
#38  &  #34

### CODE REVIEW

**Comment by CraigChamberlain** [comment]
If my other pull requests on options params for the Marker is accepted I could include so info on that.  #41 

This option is particularly useful when making your own custom popup: `popupOptions="{{'maxWidth':'none'}}"`

I could add something about the other options params that were recently added. #39

**Comment by CraigChamberlain** [comment]
Hi @antony, are these changes OK?

**Review by antony — APPROVED** [review]

**Comment by antony** [comment]
Hey - will check this when I check the other PR. Apologies for the slowness.

**Comment by evdama** [comment]
let's merge this 👍

**Comment by antony** [comment]
Further apologies! I'll be on it asap. My schedule is somewhat hectic. It's on the immediate TODO list.

**Comment by CraigChamberlain** [comment]
No problem. I'm not working on this project ATM. Thanks for finding the
time.

**Pull request merged**
